#!/usr/bin/env bash
# Generate hyprlock colors from pywal
# Produces the same variable names that the old matugen config used

COLORS="$HOME/.cache/wal/colors.json"
OUT="$HOME/.config/hypr/matugen/matugen-hyprlock.conf"

if [[ ! -f "$COLORS" ]]; then
    echo "wal colors.json not found" >&2
    exit 1
fi

mkdir -p "$(dirname "$OUT")"

bg=$(jq -r '.special.background' "$COLORS")
fg=$(jq -r '.special.foreground' "$COLORS")
c1=$(jq -r '.colors.color1' "$COLORS")
c4=$(jq -r '.colors.color4' "$COLORS")

# Convert #rrggbb → rgba(r,g,b,a) for hyprlock
hex_to_rgba() {
    local hex="${1#\#}"
    local r=$((16#${hex:0:2}))
    local g=$((16#${hex:2:2}))
    local b=$((16#${hex:4:2}))
    local a="${2:-1.0}"
    echo "rgba(${r}, ${g}, ${b}, ${a})"
}

# hyprlock uses $variable syntax like hyprland
to_argb() {
    local hex="${1#\#}"
    echo "0xff${hex}"
}

cat > "$OUT" <<EOF
# GENERATED by pywal-hyprlock-colors.sh – do not edit manually

\$primary    = rgb(${c1#\#})
\$on_primary = rgb(${fg#\#})
\$outline    = rgb(${c4#\#})
\$surface    = rgb(${bg#\#})
EOF

echo "hyprlock colors updated from pywal."
