#!/usr/bin/env bash
# robust WAL → HYPR colors script

COLORS="$HOME/.cache/wal/colors.json"
OUT="$HOME/.config/hypr/modules/hyprland-pywal.conf"

if [ ! -f "$COLORS" ]; then
  echo "wal colors.json not found" >&2
  exit 1
fi

# read hex colors from wal
bg=$(jq -r '.special.background' "$COLORS")
fg=$(jq -r '.special.foreground' "$COLORS")
c1=$(jq -r '.colors.color1' "$COLORS")
c2=$(jq -r '.colors.color2' "$COLORS")
c3=$(jq -r '.colors.color3' "$COLORS")
c4=$(jq -r '.colors.color4' "$COLORS")

# convert "#rrggbb" → "0xffrrggbb"
to_argb() {
  local hex="${1#\#}"       # remove leading #
  echo "0xff${hex}"
}

cat > "$OUT" <<EOF
# GENERATED BY hyprland-wal.sh

# core colors
\$bg      = $(to_argb "$bg")
\$fg      = $(to_argb "$fg")
\$accent  = $(to_argb "$c1")
\$accent2 = $(to_argb "$c4")

# border colors
general {
col.active_border = \$accent
col.inactive_border = \$bg
col.nogroup_border = \$bg
col.nogroup_border_active = \$accent2
}

# optional shine:
# col.active_border = \$accent \$accent2

EOF

# Also generate hyprlock colors (replaces matugen dependency)
"$HOME/.config/scripts/pywal-hyprlock-colors.sh" 2>/dev/null || true
