#!/usr/bin/env bash
# robust WAL → HYPR colors script

COLORS="$HOME/.cache/wal/colors.json"
OUT="$HOME/.config/hypr/modules/hyprland-pywal.conf"

if [ ! -f "$COLORS" ]; then
  echo "wal colors.json not found" >&2
  exit 1
fi

# read hex colors from wal
bg=$(jq -r '.special.background' "$COLORS")
fg=$(jq -r '.special.foreground' "$COLORS")
c1=$(jq -r '.colors.color1' "$COLORS")
c2=$(jq -r '.colors.color2' "$COLORS")
c3=$(jq -r '.colors.color3' "$COLORS")
c4=$(jq -r '.colors.color4' "$COLORS")

# convert "#rrggbb" → "0xffrrggbb"
to_argb() {
  local hex="${1#\#}"       # remove leading #
  echo "0xff${hex}"
}

cat > "$OUT" <<EOF
# GENERATED BY hyprland-wal.sh

# core colors
\$bg      = $(to_argb "$bg")
\$fg      = $(to_argb "$fg")
\$accent  = $(to_argb "$c1")
\$accent2 = $(to_argb "$c4")

# border colors
general {
col.active_border = \$accent2
col.inactive_border = \$bg
col.nogroup_border = \$bg
col.nogroup_border_active = \$accent2
}

EOF

# Apply border colors live without requiring a full Hyprland reload
if command -v hyprctl &>/dev/null; then
    hyprctl keyword general:col.active_border "$(to_argb "$c4")" 2>/dev/null || true
    hyprctl keyword general:col.inactive_border "$(to_argb "$bg")" 2>/dev/null || true
fi

# Generate rofi glass colors for blur transparency
# Parse bg hex into r,g,b components for rgba() format
bg_hex="${bg#\#}"
r=$((16#${bg_hex:0:2}))
g=$((16#${bg_hex:2:2}))
b=$((16#${bg_hex:4:2}))
cat > "$HOME/.cache/wal/colors-rofi-glass.rasi" <<ROFI_EOF
* {
    bg-glass:   rgba(${r}, ${g}, ${b}, 0.78);
}
ROFI_EOF

# Also generate hyprlock colors (replaces matugen dependency)
"$HOME/.config/scripts/pywal-hyprlock-colors.sh" 2>/dev/null || true
