#################
### AUTOSTART ###
#################

# Util
exec-once = hypridle
exec-once = swaync
exec-once = awww-daemon
exec-once = waybar
exec-once = swayosd-server
exec-once = wal -R

# Dynamic monitor management
exec-once = hyprdynamicmonitors run --enable-lid-events

# Clipboard history
exec-once = wl-paste --watch cliphist store

# Keyring
exec-once = dbus-update-activation-environment --all
exec-once = gnome-keyring-daemon --start --components=secrets,ssh

# Night Mode
exec = hyprshade auto
