#############################
### ENVIRONMENT VARIABLES ###
#############################

# See https://wiki.hyprland.org/Configuring/Environment-variables/
env = ELECTRON_OZONE_PLATFORM_HINT,wayland
env = XCURSOR_SIZE,32
env = HYPRCURSOR_SIZE,32
