###################
### MY PROGRAMS ###
###################

# See https://wiki.hyprland.org/Configuring/Keywords/

$terminal = kitty
$fileManager = nautilus
$menu = rofi -show drun
$browser = zen-browser
$discord = webcord
# $codeEditor = vscodium --ozone-platform=wayland
$codeEditor = code
$mail = thunderbird
$notes = obsidian
$documentEditor = libreoffice
