###################
### MY PROGRAMS ###
###################

# See https://wiki.hyprland.org/Configuring/Keywords/

$terminal = kitty
$fileManager = thunar
$menu = rofi -show drun
$browser = zen-browser
$discord = webcord
$vscode = vscodium --ozone-platform=wayland
$mail = thunderbird
$notes = obsidian
