[mgr]
cwd = { fg = "#2E6062" }

hovered         = { fg = "#081517", bg = "#2E6062" }
preview_hovered = { underline = true }

find_keyword  = { fg = "#1B4751", italic = true }
find_position = { fg = "#658D6D", bg = "reset", italic = true }

marker_selected = { fg = "#133548", bg = "#133548" }
marker_copied   = { fg = "#1B4751", bg = "#1B4751" }
marker_cut      = { fg = "#102A2D", bg = "#102A2D" }

tab_active   = { fg = "#081517", bg = "#2E6062" }
tab_inactive = { fg = "#1F292B", bg = "#081517" }
tab_width    = 1

border_symbol = "│"
border_style  = { fg = "#1F292B" }

syntect_theme = ""

[status]
separator_open  = ""
separator_close = ""
separator_style = { fg = "#081517", bg = "#081517" }

mode_normal = { fg = "#081517", bg = "#7C8975", bold = true }
mode_select = { fg = "#081517", bg = "#133548", bold = true }
mode_unset  = { fg = "#081517", bg = "#658D6D", bold = true }

progress_label  = { fg = "#ACC3A6", bold = true }
progress_normal = { fg = "#2E6062",    bg = "#081517" }
progress_error  = { fg = "#102A2D", bg = "#081517" }

permissions_t = { fg = "#133548" }
permissions_r = { fg = "#1B4751" }
permissions_w = { fg = "#102A2D" }
permissions_x = { fg = "#2E6062" }
permissions_s = { fg = "#1F292B" }

[input]
border   = { fg = "#2E6062" }
title    = {}
value    = {}
selected = { reversed = true }

[select]
border   = { fg = "#2E6062" }
active   = { fg = "#1B4751" }
inactive = {}

[tasks]
border  = { fg = "#2E6062" }
title   = {}
hovered = { underline = true }

[which]
cols            = 3
mask            = { bg = "#081517" }
cand            = { fg = "#133548" }
rest            = { fg = "#1F292B" }
desc            = { fg = "#1B4751" }
separator       = "  "
separator_style = { fg = "#081517" }

[help]
on      = { fg = "#1B4751" }
exec    = { fg = "#133548" }
desc    = { fg = "#1F292B" }
hovered = { bg = "#081517", bold = true }
footer  = { fg = "#081517", bg = "#ACC3A6" }

[filetype]
rules = [
    { mime = "image/*",                    fg = "#133548" },
    { mime = "video/*",                    fg = "#1B4751" },
    { mime = "audio/*",                    fg = "#1B4751" },
    { mime = "application/zip",            fg = "#658D6D" },
    { mime = "application/gzip",           fg = "#658D6D" },
    { mime = "application/x-tar",          fg = "#658D6D" },
    { mime = "application/x-bzip",         fg = "#658D6D" },
    { mime = "application/x-bzip2",        fg = "#658D6D" },
    { mime = "application/x-7z-compressed",fg = "#658D6D" },
    { mime = "application/x-rar",          fg = "#658D6D" },
    { name = "*",  fg = "#ACC3A6" },
    { name = "*/", fg = "#2E6062" },
]
