[mgr]
cwd = { fg = "#4C6A52" }

hovered         = { fg = "#181A1C", bg = "#4C6A52" }
preview_hovered = { underline = true }

find_keyword  = { fg = "#3B5040", italic = true }
find_position = { fg = "#7E8351", bg = "reset", italic = true }

marker_selected = { fg = "#1B424B", bg = "#1B424B" }
marker_copied   = { fg = "#3B5040", bg = "#3B5040" }
marker_cut      = { fg = "#17342C", bg = "#17342C" }

tab_active   = { fg = "#181A1C", bg = "#4C6A52" }
tab_inactive = { fg = "#90988D", bg = "#3E4143" }
tab_width    = 1

border_symbol = "│"
border_style  = { fg = "#90988D" }

syntect_theme = ""

[status]
separator_open  = ""
separator_close = ""
separator_style = { fg = "#3E4143", bg = "#3E4143" }

mode_normal = { fg = "#181A1C", bg = "#81927C", bold = true }
mode_select = { fg = "#181A1C", bg = "#1B424B", bold = true }
mode_unset  = { fg = "#181A1C", bg = "#7E8351", bold = true }

progress_label  = { fg = "#E2EAE0", bold = true }
progress_normal = { fg = "#4C6A52",    bg = "#3E4143" }
progress_error  = { fg = "#17342C", bg = "#3E4143" }

permissions_t = { fg = "#1B424B" }
permissions_r = { fg = "#3B5040" }
permissions_w = { fg = "#17342C" }
permissions_x = { fg = "#4C6A52" }
permissions_s = { fg = "#90988D" }

[input]
border   = { fg = "#4C6A52" }
title    = {}
value    = {}
selected = { reversed = true }

[select]
border   = { fg = "#4C6A52" }
active   = { fg = "#3B5040" }
inactive = {}

[tasks]
border  = { fg = "#4C6A52" }
title   = {}
hovered = { underline = true }

[which]
cols            = 3
mask            = { bg = "#3E4143" }
cand            = { fg = "#1B424B" }
rest            = { fg = "#90988D" }
desc            = { fg = "#3B5040" }
separator       = "  "
separator_style = { fg = "#3E4143" }

[help]
on      = { fg = "#3B5040" }
exec    = { fg = "#1B424B" }
desc    = { fg = "#90988D" }
hovered = { bg = "#3E4143", bold = true }
footer  = { fg = "#3E4143", bg = "#E2EAE0" }

[filetype]
rules = [
    { mime = "image/*",                    fg = "#1B424B" },
    { mime = "video/*",                    fg = "#3B5040" },
    { mime = "audio/*",                    fg = "#3B5040" },
    { mime = "application/zip",            fg = "#7E8351" },
    { mime = "application/gzip",           fg = "#7E8351" },
    { mime = "application/x-tar",          fg = "#7E8351" },
    { mime = "application/x-bzip",         fg = "#7E8351" },
    { mime = "application/x-bzip2",        fg = "#7E8351" },
    { mime = "application/x-7z-compressed",fg = "#7E8351" },
    { mime = "application/x-rar",          fg = "#7E8351" },
    { name = "*",  fg = "#E2EAE0" },
    { name = "*/", fg = "#4C6A52" },
]
