################
### MONITORS ###
################

monitor = eDP-1, disable
monitor = desc:Microstep Optix MAG24C 0000000000001, preffered, -1920x360, auto
monitor = desc:Microstep G274QPF-QD CC2H252C00385, 2560x1440@144, 0x0, auto