################
### MONITORS ###
################
monitor = eDP-1, disable
monitor = desc:Microstep Optix MAG24C 0000000000001, 1920x1080@120, -1920x0, auto, cm, auto
monitor = desc:Microstep G274QPF-QD CC2H252C00385, 2560x1440@144, 0x0, auto, cm, auto
