################
### MONITORS ###
################
monitor = eDP-1, disable
monitor = desc:Microstep Optix MAG24C 0000000000001, preferred, -1920x240, auto
monitor = desc:Microstep G274QPF-QD CC2H252C00385, preferred, 0x0, auto, cm, auto
